### ISSUE TITLE
Suggested addition to apply.reconstruction

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#10]
Would it be easy to add a 'total length' attribute to the output returned by apply.reconstruction?

At present the output of print.states.matrix prints "Tree length is: 5"; it would be handy if this value could be obtained from NA_matrix$length, rather than having to be manually counted by summing the applicable regions and state changes.

**Comment by TGuillerme** [comment]
Fixed and updated to `v0.2.2`. You can now get the total length from `apply.reconstruction` by accessing `NA_matrix$length`.
