### ISSUE TITLE
use.edge.length cannot be overridden

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#15]
I'm using `plot.states.matrix` to visualise the output of the matrix with a large tree (79 taxa).  Many of the node labels are bunched up to the right of the screen and overlap the tip labels.  I'm trying to space things out a little, but if I set `use.edge.length=TRUE` then R sends the message

`Error in plot.phylo(tree, show.tip.label = show.tip.label, type = "phylogram",  : 
  formal argument "use.edge.length" matched by multiple actual arguments`

At https://github.com/TGuillerme/Inapp/blob/master/R/plot.algorithm.R : line 141 could `use.edge.length = FALSE` be replaced with `use.edge.length = use.edge.length`, with a default value of 'FALSE' being set in an appropriate place?

**Comment by TGuillerme** [comment]
Good call! It should be fixed now.
