### ISSUE TITLE
Return value of apply.reconstruction not documented

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#18]
I expected `length(recon$length) == length(c(recon$regions, recon$changes))`
i.e. the 'length' value to concatenate the regions and changes information; in practice though it looks to me like it just replicates the value of `recon$changes`. It would be useful to document the structure of the list returned by `recon = apply.reconstruction(...)` so that the purposes of each of these values is apparent.

**Comment by TGuillerme** [comment]
Done in 0.2.2
