### ISSUE TITLE
Cannot pass "passes = 1:4"

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#19]
It would be nice if the code below worked:

```r
recon <- apply.reconstruction(tree, data, method='NA')
plot(recon, passes=1:4)
```

Currently one must pass `passes=c(1, 2, 3, 4)` or receive the error `passes argument must be any integer(s) between 1 and 4.`

**Comment by TGuillerme** [comment]
Fixed in next version (will be 0.2.2)
