### ISSUE TITLE
Algorithm description doesn't match implementation

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#2]
With tree
(((a,b),(c,d)), e);
and character string
0----

node n8 is reconstructed as -0 on downpass 1.
Following the written algorithm:
1. Enter on the cherry subtended by n8
2. No token in common: go to 4
4. any descendents have an applicable token: yes (tip a). So node's state set to be the union of its descendants without any inapplicable token (= 0... the implementation [correctly?] reconstructs "-0" instead)

On closer inspection, the IF in step 4 will always be TRUE, meaning that the ELSE will never be triggered.
Should the step read: "_set_ the node's state to be the intersection of its descendants. **Then** _go_ to 5. ?

**Comment by TGuillerme** [comment]
I think It's the idea that if you have a pair of descendants coded as `A-` and `B-`, it should reconstruct as `AB`, `A-`/`A` and `-` as `A` but `-` and `-` as `-`. Worth checking together next week.

**Comment by TGuillerme** [comment]
I've updated the English version. It might make more sense now.

**Comment by ms609** [comment]
Yes, I can follow it now.  But there are still a few areas where it doesn't match the implementation.
