### ISSUE TITLE
"Applicable regions" causes error if ticked

### ISSUE THREAD

**Issue by ms609** [TGuillerme/Inapp#6]
If "Applicable regions" is ticked and the reconstruction method is switched to Normal Fitch - An Extra State, the tree disappears and the text "Error: replacement has length zero" appears.

![image](https://cloud.githubusercontent.com/assets/1695515/25709841/612acc06-30e2-11e7-8dc0-bdebf871d781.png)

**Comment by TGuillerme** [comment]
Fixed in v0.2.1 on master. Thanks for finding that one!
